security:
  authorization: enabled

net:
  bindIp: 0.0.0.0

systemLog:
  quiet: true
  verbosity: 0
  component:
      accessControl:
         verbosity: -1
      command:
         verbosity: -1
      storage:
         verbosity: -1         

setParameter:
  enableDetailedConnectionHealthMetricLogLines: false