import WebsiteTransition from '@/components/ui/transition/WebsiteTransition';
import Heading from '@/components/ui/Heading';
import WebsiteFooter from '../WebsiteFooter';
import Text from '@/components/ui/Text';
import ScrollWrapper from '@/components/ui/layout/scroll/ScrollWrapper';

export default function PrivacyPage() {
  return (
    <WebsiteTransition>
      <div className='flex-1 flex flex-col w-full h-full overflow-hidden -mt-[59px]'>
        <ScrollWrapper className='z-10'>
          <div className='flex flex-col flex-1 w-full min-h-fit items-center relative z-10'>
            <Heading level={1} className='mt-20 mb-8'>Privacy Policy</Heading>        
            
            <div className='max-w-4xl mx-auto px-6 space-y-8 mb-16'>
              <Text variant='small' className='text-center'>Last updated: September 15, 2025</Text>
              
              <Text variant='body'>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </Text>
              
              <Text variant='body'>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </Text>

              <div className='space-y-6'>
                <Heading level={2}>Interpretation and Definitions</Heading>
                
                <div className='space-y-4'>
                  <Heading level={3}>Definitions</Heading>
                  <Text variant='body'>For the purposes of this Privacy Policy:</Text>
                  
                  <div className='space-y-3'>
                    <Text variant='body'><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</Text>
                    <Text variant='body'><strong>Company</strong> (referred to as either &apos;the Company&apos;, &apos;We&apos;, &apos;Us&apos; or &apos;Our&apos; in this Agreement) refers to mystyc.</Text>
                    <Text variant='body'><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</Text>
                    <Text variant='body'><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Text>
                    <Text variant='body'><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</Text>
                    <Text variant='body'><strong>Service</strong> refers to the Website.</Text>
                    <Text variant='body'><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</Text>
                    <Text variant='body'><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
                    <Text variant='body'><strong>Website</strong> refers to mystyc, accessible from https://mystyc.app</Text>
                    <Text variant='body'><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
                  </div>
                </div>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Collecting and Using Your Personal Data</Heading>
                
                <div className='space-y-4'>
                  <Heading level={3}>Types of Data Collected</Heading>
                  
                  <div className='space-y-4'>
                    <Heading level={4}>Personal Data</Heading>
                    <Text variant='body'>
                      While using Our astrological services, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                    </Text>
                    
                    <div className='ml-4 space-y-2'>
                      <Text variant='body'>• Email address</Text>
                      <Text variant='body'>• First name and last name</Text>
                      <Text variant='body'>• Birth date, birth time, and birth location</Text>
                      <Text variant='body'>• Billing information for payments</Text>
                      <Text variant='body'>• Usage Data</Text>
                    </div>
                  </div>

                  <div className='space-y-4'>
                    <Heading level={4}>Usage Data</Heading>
                    <Text variant='body'>Usage Data is collected automatically when using the Service.</Text>
                    <Text variant='body'>
                      Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    </Text>
                    <Text variant='body'>
                      When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                    </Text>
                  </div>
                </div>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Tracking Technologies and Cookies</Heading>
                <Text variant='body'>
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
                </Text>
                
                <Text variant='body'>We use both Session and Persistent Cookies for the purposes set out below:</Text>
                
                <div className='space-y-4'>
                  <div>
                    <Text variant='body'><strong>Necessary / Essential Cookies</strong></Text>
                    <Text variant='body'>Type: Session Cookies</Text>
                    <Text variant='body'>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</Text>
                  </div>
                  
                  <div>
                    <Text variant='body'><strong>Functionality Cookies</strong></Text>
                    <Text variant='body'>Type: Persistent Cookies</Text>
                    <Text variant='body'>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</Text>
                  </div>
                </div>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Use of Your Personal Data</Heading>
                <Text variant='body'>The Company may use Personal Data for the following purposes:</Text>
                
                <div className='ml-4 space-y-3'>
                  <Text variant='body'>• To provide and maintain our astrological services, including to monitor the usage of our Service</Text>
                  <Text variant='body'>• To generate astrological charts and interpretations: We use your birth information (date, time, location) to create personalized astrological content</Text>
                  <Text variant='body'>• To manage Your Account: to manage Your registration as a user of the Service</Text>
                  <Text variant='body'>• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased</Text>
                  <Text variant='body'>• To contact You: To contact You by email or other forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services</Text>
                  <Text variant='body'>• To provide You with news, special offers and general information about other goods, services and events which we offer unless You have opted not to receive such information</Text>
                  <Text variant='body'>• To manage Your requests: To attend and manage Your requests to Us</Text>
                </div>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Sharing Your Personal Information</Heading>
                <Text variant='body'>We may share Your personal information in the following situations:</Text>
                
                <div className='ml-4 space-y-3'>
                  <Text variant='body'>• <strong>With Service Providers:</strong> We use third-party services including Google Firebase for authentication and analytics, payment processors for billing, and AI services for chart calculations. These services may have access to your information as needed to provide their functionality.</Text>
                  <Text variant='body'>• <strong>For business transfers:</strong> We may share or transfer Your personal information in connection with any merger, sale of Company assets, financing, or acquisition</Text>
                  <Text variant='body'>• <strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent</Text>
                </div>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Transfer of Your Personal Data</Heading>
                <Text variant='body'>
                  Your information, including Personal Data, may be transferred to and processed in the United States and other countries where our service providers operate, including for payment processing, cloud hosting, and AI-powered chart generation. Data protection laws in these jurisdictions may differ from those in Your jurisdiction.
                </Text>
                <Text variant='body'>
                  The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                </Text>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Retention of Your Personal Data</Heading>
                <Text variant='body'>
                  The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                </Text>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Delete Your Personal Data</Heading>
                <Text variant='body'>
                  You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
                </Text>
                <Text variant='body'>
                  You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
                </Text>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Security of Your Personal Data</Heading>
                <Text variant='body'>
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </Text>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Children&apos;s Privacy</Heading>
                <Text variant='body'>
                  Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
                </Text>
              </div>

              <div className='space-y-6'>
                <Heading level={2}>Changes to this Privacy Policy</Heading>
                <Text variant='body'>
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the &apos;Last updated&apos; date at the top of this Privacy Policy.
                </Text>
              </div>

            </div>
          </div>
          <WebsiteFooter />
        </ScrollWrapper>
      </div>
    </WebsiteTransition>
  )
}